# Generated by Django 5.0.6 on 2026-08-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inbox', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='customers', to='inbox.label'),
        ),
        migrations.AddField(
            model_name='customer',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='customerchannel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customertimelineevent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'name'], name='customers_workspa_7db0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'phone'], name='customers_workspa_585f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'email'], name='customers_workspa_75c5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='customerchannel',
            index=models.Index(fields=['channel', 'external_id'], name='customer_ch_channel_ee6e37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerchannel',
            unique_together={('channel', 'external_id')},
        ),
    ]
