# Generated by Django 5.0.6 on 2026-09-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerchannel',
            name='profile_url',
            field=models.TextField(blank=True),
        ),
    ]
