# Generated by Django 5.0.6 on 2026-08-22 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebchatConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('title', models.CharField(default='Chat with us', max_length=100)),
                ('welcome_message', models.TextField(default='Hi! How can we help you today?')),
                ('offline_message', models.TextField(default="We're offline. Please leave a message and we'll get back to you.")),
                ('primary_color', models.CharField(default='#6366f1', max_length=20)),
                ('position', models.CharField(default='bottom-right', max_length=20)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webchat_config', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'webchat_configs',
            },
        ),
        migrations.CreateModel(
            name='WebchatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('visitor_name', models.CharField(blank=True, default='Anonymous', max_length=255)),
                ('visitor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('visitor_phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_online', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webchat_sessions', to='customers.customer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webchat_sessions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'webchat_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
