# Generated by Django 5.0.6 on 2026-08-22 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'integration_type')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integration')),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='received', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='webhook_eve_source_a5b0cf_idx'), models.Index(fields=['external_id'], name='webhook_eve_externa_c34803_idx')],
            },
        ),
    ]
