# Generated by Django 5.0.6 on 2026-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['workspace', 'integration_type', 'status'], name='integration_workspa_059fe9_idx'),
        ),
    ]
