# Generated by Django 5.0.6 on 2026-09-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
