# Generated by Django 5.0.6 on 2026-08-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('customers', '0001_initial'),
        ('inbox', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='inbox.conversation'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['workspace', 'status'], name='complaints_workspa_044bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['workspace', 'priority'], name='complaints_workspa_de7a00_idx'),
        ),
    ]
