# Generated by Django 5.0.6 on 2026-08-22 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('channel', models.CharField(max_length=20)),
                ('post_id', models.CharField(blank=True, default='', max_length=255)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('author_external_id', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('reply', models.TextField(blank=True, default='')),
                ('is_replied', models.BooleanField(default=False)),
                ('is_auto_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('keyword', 'Keyword'), ('ai', 'AI'), ('comment', 'Comment')], default='keyword', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('response_template', models.TextField(blank=True, default='')),
                ('use_ai', models.BooleanField(default=False)),
                ('channel', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'automation_rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
