# Generated by Django 5.0.6 on 2026-08-22 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('auto_reply', 'Auto Reply'), ('language_detection', 'Language Detection'), ('complaint_detection', 'Complaint Detection'), ('intent_detection', 'Intent Detection'), ('product_recognition', 'Product Recognition'), ('handoff', 'Human Handoff'), ('error', 'Error')], max_length=30)),
                ('input_text', models.TextField(blank=True, default='')),
                ('output_text', models.TextField(blank=True, default='')),
                ('detected_language', models.CharField(blank=True, default='', max_length=10)),
                ('detected_intent', models.CharField(blank=True, default='', max_length=100)),
                ('is_complaint', models.BooleanField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInstructions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_description', models.TextField(blank=True, default='')),
                ('tone', models.CharField(default='polite, professional', max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('greeting', models.TextField(blank=True, default='')),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('delivery_policy', models.TextField(blank=True, default='')),
                ('payment_policy', models.TextField(blank=True, default='')),
                ('return_policy', models.TextField(blank=True, default='')),
                ('refund_policy', models.TextField(blank=True, default='')),
                ('cancellation_policy', models.TextField(blank=True, default='')),
                ('escalation_rules', models.JSONField(blank=True, default=list)),
                ('prohibited_responses', models.JSONField(blank=True, default=list)),
                ('sales_strategy', models.TextField(blank=True, default='')),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('custom_instructions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_instructions',
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('off', 'Off'), ('suggest_only', 'Suggest Only'), ('auto_reply', 'Auto Reply'), ('hybrid', 'Hybrid')], default='suggest_only', max_length=20)),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(blank=True, default='')),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.PositiveIntegerField(default=2048)),
                ('enable_vision', models.BooleanField(default=True)),
                ('enable_complaint_detection', models.BooleanField(default=True)),
                ('enable_language_detection', models.BooleanField(default=True)),
                ('enable_human_handoff', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('safety_rules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_settings',
            },
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ai_replies', models.PositiveIntegerField(default=0)),
                ('ai_suggestions', models.PositiveIntegerField(default=0)),
                ('comment_automation', models.PositiveIntegerField(default=0)),
                ('vision_requests', models.PositiveIntegerField(default=0)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'ai_usage',
                'ordering': ['-date'],
            },
        ),
    ]
