# Generated by Django 5.0.6 on 2026-08-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('inbox', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievent',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_events', to='inbox.conversation'),
        ),
        migrations.AddField(
            model_name='aievent',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_events', to='inbox.message'),
        ),
        migrations.AddField(
            model_name='aievent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='aiinstructions',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_instructions', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='aievent',
            index=models.Index(fields=['workspace', 'event_type'], name='ai_events_workspa_5f5cbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiusage',
            unique_together={('workspace', 'date')},
        ),
    ]
